workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^topic\/.*/ && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

stages:
  - preparation
  - check
  - test
  - build
  - deploy

javascript:
  stage: preparation
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:15
  cache:
    paths:
      - .npm/
  script:
    - npm install --cache .npm --prefer-offline
    - npx gulp
  artifacts:
    paths:
      - static/js/
    expire_in: 1 week

.check:
  stage: check
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/ci

check-flake8:
  extends: .check
  script:
    - flake8

check-isort:
  extends: .check
  script:
    - isort -c .

test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.9
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  script:
    - pip install -r requirements.txt -r requirements-test.txt
    - coverage run --omit=*/tests/* -m xmlrunner discover -v --output-file junit.xml
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: build
  image: docker:stable
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: website
  services:
    - docker:dind
  script:
    - docker build --pull -t $IMAGE:$TAG .
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

build-critical-css:
  stage: build
  image: docker:stable
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: critical-css
  services:
    - docker:dind
  script:
    - docker build --pull -t $IMAGE:$TAG critical-css/.
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy:
  stage: deploy
  timeout: 730 hours
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: website
  needs:
    - build
    - test
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_IO_USER" -p "$DOCKER_IO_PASSWORD" $DOCKER_IO_REGISTRY
  script:
    - docker push $IMAGE:$TAG
    - docker push $$DOCKER_IO_USER/$IMAGE:$TAG


deploy-critical-css:
  stage: deploy
  timeout: 730 hours
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: critical-css
  needs:
    - build-critical-css
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_IO_USER" -p "$DOCKER_IO_PASSWORD" $DOCKER_IO_REGISTRY
  script:
    - docker push $IMAGE:$TAG
    - docker push $$DOCKER_IO_USER/$IMAGE:$TAG
