name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Website image
        run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/website:latest

      - name: Push Docker Website image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/website:latest

      - name: Build Docker Critical-CSS image
        run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/critical-css:latest

      - name: Push Docker Critical-CSS image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/critical-css:latest
